### ISSUE TITLE
Not working with 3.6 update

### ISSUE THREAD

**Issue by NoNick96** [DetectiveSquirrel/Get-Chaos-Value#5]
Log Entry : 10:22:21 Sunday, 17 March, 2019
 Method error: Initialise : System.Net.WebException: the remote name could not be resolved: 'd1u5p3l4wpay3k.cloudfront.net'
   in System.Net.WebClient.DownloadFile(Uri address, String fileName)
   in Ninja_Price.Main.Main.DownloadChaosIcon() in D:\Coding\Source Files\PoeHUD Plugins\Get-Chaos-Value\src\Ninja Price\Methods\Methods.cs:line 58
   in Ninja_Price.Main.Main.Initialise() in D:\Coding\Source Files\PoeHUD Plugins\Get-Chaos-Value\src\Ninja Price\Main\Main.cs:line 50
   in PoeHUD.Plugins.BasePlugin._ForceInitialize()

After this error, PoEHUD crashes.

**Comment by Cushie** [comment]
This is due to methods.cs:58 - It's trying to get the chaos orb icon but the url is no longer working (https://d1u5p3l4wpay3k.cloudfront.net/pathofexile_gamepedia/9/9c/Chaos_Orb_inventory_icon.png)

A quick fix for this for users is to download the icon from somewhere else (https://gamepedia.cursecdn.com/pathofexile_gamepedia/9/9c/Chaos_Orb_inventory_icon.png) and save this image to your Get-Chaos-Value/images folder.

The plugin will then work fine.
